{% set name = "cmyt" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cmyt-{{ version }}.tar.gz
  sha256: a24c5cf765458fa8ed6b70c37d9531cdd8ae79ae96f916d26a3c3c169b18346e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0

test:
  imports:
    - cmyt
    - cmyt.colormaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yt-project/yt
  summary: A collection of Matplotlib colormaps from the yt project
  dev_url: https://github.com/yt-project/cmyt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
