{% set name = "cmyt" %}
{% set version = "2.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cmyt-{{ version }}.tar.gz
  sha256: cf308415401c615dffded3033be575373553573740298e44ef4b016ffd99a9be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0

test:
  imports:
    - cmyt
    - cmyt.colormaps
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/yt-project/yt
  summary: A collection of Matplotlib colormaps from the yt project
  dev_url: https://github.com/yt-project/cmyt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
