{% set name = "cmyt" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/cmyt-{{ version }}.tar.gz
  sha256: 3cb83424adf95337840d9dd6eef5f0e2f6d53e9618cd11a2cb31218227e40b27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0

test:
  imports:
    - cmyt
    - cmyt.colormaps
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/yt-project/yt
  summary: A collection of Matplotlib colormaps from the yt project
  dev_url: https://github.com/yt-project/cmyt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
