schema_version: 1

context:
  name: cmyt
  version: "2.0.2"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cmyt-${{ version }}.tar.gz
  sha256: cf308415401c615dffded3033be575373553573740298e44ef4b016ffd99a9be

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0

tests:
  - python:
      imports:
        - cmyt
        - cmyt.colormaps
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A collection of Matplotlib colormaps from the yt project
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/yt-project/yt
  repository: https://github.com/yt-project/cmyt/

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
